version: '3'

services:
  env_ore:
    image: env_ore:${ORE_TAG}
    cap_drop:
      - NET_RAW
    volumes:
      - /home/shared/cache/ore_env:/ccache
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE
      args:
        - quantlib_version=${QL_TAG}
        - cmake_build_type=${CMAKE_BUILD_TYPE}
        - num_cores=${NUM_CORES}
