name: C/C++ CI

on:
  push:
    branches: master
  pull_request:
    branches: master
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - .github/workflows/linux_build.yaml
      - ./App/**
      - ./OREAnalytics/**
      - '!./OREAnalytics/doc/**'
      - ./OREData/**
      - '!./OREData/doc/**'
      - ./ORETest/**
      - ./QuantExt/**
      - '!./QuantExt/doc/**'
      - CMakeLists.txt
  workflow_dispatch:

jobs:
  build:
    name: building
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: get QuantLib
      run: |
        git submodule update --init
    - name: Set up Boost
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev libboost-test-dev ninja-build
    - name: cmake configure
      run : mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release -DQL_BUILD_EXAMPLES=false -DQL_BUILD_TEST_SUITE=false -DQL_BUILD_BENCHMARK=false -DQL_ENABLE_SESSIONS=true -DORE_BUILD_DOC=false -G "Ninja" ..
    - name: cmake build
      run: cd build/; pwd; cmake --build . -j $(nproc)
